// Indent status code IDs (mst_indent_statuses.codeId)
const STATUS_MATERIAL_ISSUE_CODE_ID = 1;
const STATUS_L1_APPROVAL_PENDING_CODE_ID = 2;
const STATUS_L1_APPROVED_CODE_ID = 3;
const STATUS_PO_GENERATED_CODE_ID = 4;
const STATUS_COMPLETED_CODE_ID = 5;
const STATUS_REJECTED_CODE_ID = 6;
const STATUS_L1_L2_APPROVED_CODE_ID = 7;
const STATUS_PARTIALLY_APPROVED_CODE_ID = 8;

// Purchase order types (txn_purchase_orders.type)
const PO_TYPE_DRAFT = 1;
const PO_TYPE_ORDER = 2;

// Purchase order status code IDs (mst_purchase_order_status.code_id)
const PO_STATUS_L1_APPROVAL_PENDING_CODE_ID = 1;
const PO_STATUS_L2_APPROVAL_PENDING_CODE_ID = 2;
const PO_STATUS_GENERATED_CODE_ID = 3;
const PO_STATUS_REJECTED_CODE_ID = 4;
const PO_STATUS_DRAFT_CODE_ID = 5;

module.exports = {
    STATUS_MATERIAL_ISSUE_CODE_ID,
    STATUS_L1_APPROVAL_PENDING_CODE_ID,
    STATUS_L1_APPROVED_CODE_ID,
    STATUS_PO_GENERATED_CODE_ID,
    STATUS_COMPLETED_CODE_ID,
    STATUS_REJECTED_CODE_ID,
    STATUS_L1_L2_APPROVED_CODE_ID,
    STATUS_PARTIALLY_APPROVED_CODE_ID,
    PO_TYPE_DRAFT,
    PO_TYPE_ORDER,
    PO_STATUS_L1_APPROVAL_PENDING_CODE_ID,
    PO_STATUS_L2_APPROVAL_PENDING_CODE_ID,
    PO_STATUS_GENERATED_CODE_ID,
    PO_STATUS_REJECTED_CODE_ID,
    PO_STATUS_DRAFT_CODE_ID,
};
